"""Generate P6's observed silent fixture paths; never an oracle about PDF content."""
import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path[:0] = [str(ROOT / "src"), str(ROOT / "packages/vdi2770/src")]

from vdi2770.validate import report as rendering
from vdi2770.validate.runner import check_file

OUT = ROOT / "docs/silent-paths.json"


def build():
    cases = []
    for path in sorted((ROOT / "tests/fixtures/pages").glob("*.zip")):
        report = check_file(str(path))
        if not any(f.rule.id == "P6" for f in report.findings):
            cases.append({
                "fixture": str(path.relative_to(ROOT)),
                "otherRules": sorted({f.rule.id for f in report.findings}),
                "complete": json.loads(rendering.as_json(report))["read"]["complete"],
            })
    return {"_about": "Generated by tools/silent_paths.py: P6 emitted no finding on these fixtures. "
                     "Silence can mean agreement, an ineligible comparison, or an existing refusal; "
                     "it does not establish rendered page counts.",
            "cases": cases}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    payload = json.dumps(build(), ensure_ascii=False, indent=2) + "\n"
    if args.write:
        OUT.write_text(payload, encoding="utf-8")
        print(f"wrote {OUT.relative_to(ROOT)}")
        return 0
    if not OUT.exists() or OUT.read_text(encoding="utf-8") != payload:
        print("docs/silent-paths.json is stale; run tools/silent_paths.py --write", file=sys.stderr)
        return 1
    print("silent P6 paths match their generated fixtures")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
